name: Create PR

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "dist/**"

jobs:
  pull-request:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@master
        with:
          timeZone: UTC
          format: "YYYY-MM-DD-HH-mm-ss"
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create pull request
        uses: mohsen-deriv/create-pr-action@0.0.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_folder: "dist"
          destination_repo: "mohsen-deriv/learn-actions"
          destination_base_branch: "main"
          destination_head_branch: ${{format( 'update-quill-tailwind-tokens-{0}', steps.time.outputs.time )}}
          commit_message_title: "chore"
          user_email: "mohsen@regentmarkets.com"
          user_name: "mohsen-deriv"
          pull_request_reviewers: "mohsen-deriv,prince-deriv,yashim-deriv"
